name: "Veracode Safe to Deploy"
description: "Standalone Github Action for blocking deployment"
author: "Narayanan Chandran"

inputs:
  vid:
    description: "Veracode API ID"
    required: true

  vkey:
    description: "Veracode API Key"
    required: true

runs:
  using: "node24"
  main: "dist/index.js"